/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TradeIntelligenceRouteImport } from './routes/trade-intelligence'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as LogisticsRouteImport } from './routes/logistics'
import { Route as GalleryRouteImport } from './routes/gallery'
import { Route as ExportsRouteImport } from './routes/exports'
import { Route as DivisionsRouteImport } from './routes/divisions'
import { Route as DigitalRouteImport } from './routes/digital'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as ConsultingRouteImport } from './routes/consulting'
import { Route as BlogRouteImport } from './routes/blog'
import { Route as AcademyRouteImport } from './routes/academy'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'

const TradeIntelligenceRoute = TradeIntelligenceRouteImport.update({
  id: '/trade-intelligence',
  path: '/trade-intelligence',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const LogisticsRoute = LogisticsRouteImport.update({
  id: '/logistics',
  path: '/logistics',
  getParentRoute: () => rootRouteImport,
} as any)
const GalleryRoute = GalleryRouteImport.update({
  id: '/gallery',
  path: '/gallery',
  getParentRoute: () => rootRouteImport,
} as any)
const ExportsRoute = ExportsRouteImport.update({
  id: '/exports',
  path: '/exports',
  getParentRoute: () => rootRouteImport,
} as any)
const DivisionsRoute = DivisionsRouteImport.update({
  id: '/divisions',
  path: '/divisions',
  getParentRoute: () => rootRouteImport,
} as any)
const DigitalRoute = DigitalRouteImport.update({
  id: '/digital',
  path: '/digital',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const ConsultingRoute = ConsultingRouteImport.update({
  id: '/consulting',
  path: '/consulting',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogRoute = BlogRouteImport.update({
  id: '/blog',
  path: '/blog',
  getParentRoute: () => rootRouteImport,
} as any)
const AcademyRoute = AcademyRouteImport.update({
  id: '/academy',
  path: '/academy',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/academy': typeof AcademyRoute
  '/blog': typeof BlogRoute
  '/consulting': typeof ConsultingRoute
  '/contact': typeof ContactRoute
  '/digital': typeof DigitalRoute
  '/divisions': typeof DivisionsRoute
  '/exports': typeof ExportsRoute
  '/gallery': typeof GalleryRoute
  '/logistics': typeof LogisticsRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/trade-intelligence': typeof TradeIntelligenceRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/academy': typeof AcademyRoute
  '/blog': typeof BlogRoute
  '/consulting': typeof ConsultingRoute
  '/contact': typeof ContactRoute
  '/digital': typeof DigitalRoute
  '/divisions': typeof DivisionsRoute
  '/exports': typeof ExportsRoute
  '/gallery': typeof GalleryRoute
  '/logistics': typeof LogisticsRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/trade-intelligence': typeof TradeIntelligenceRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/academy': typeof AcademyRoute
  '/blog': typeof BlogRoute
  '/consulting': typeof ConsultingRoute
  '/contact': typeof ContactRoute
  '/digital': typeof DigitalRoute
  '/divisions': typeof DivisionsRoute
  '/exports': typeof ExportsRoute
  '/gallery': typeof GalleryRoute
  '/logistics': typeof LogisticsRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/trade-intelligence': typeof TradeIntelligenceRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/academy'
    | '/blog'
    | '/consulting'
    | '/contact'
    | '/digital'
    | '/divisions'
    | '/exports'
    | '/gallery'
    | '/logistics'
    | '/sitemap.xml'
    | '/trade-intelligence'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/academy'
    | '/blog'
    | '/consulting'
    | '/contact'
    | '/digital'
    | '/divisions'
    | '/exports'
    | '/gallery'
    | '/logistics'
    | '/sitemap.xml'
    | '/trade-intelligence'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/academy'
    | '/blog'
    | '/consulting'
    | '/contact'
    | '/digital'
    | '/divisions'
    | '/exports'
    | '/gallery'
    | '/logistics'
    | '/sitemap.xml'
    | '/trade-intelligence'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AcademyRoute: typeof AcademyRoute
  BlogRoute: typeof BlogRoute
  ConsultingRoute: typeof ConsultingRoute
  ContactRoute: typeof ContactRoute
  DigitalRoute: typeof DigitalRoute
  DivisionsRoute: typeof DivisionsRoute
  ExportsRoute: typeof ExportsRoute
  GalleryRoute: typeof GalleryRoute
  LogisticsRoute: typeof LogisticsRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  TradeIntelligenceRoute: typeof TradeIntelligenceRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/trade-intelligence': {
      id: '/trade-intelligence'
      path: '/trade-intelligence'
      fullPath: '/trade-intelligence'
      preLoaderRoute: typeof TradeIntelligenceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/logistics': {
      id: '/logistics'
      path: '/logistics'
      fullPath: '/logistics'
      preLoaderRoute: typeof LogisticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gallery': {
      id: '/gallery'
      path: '/gallery'
      fullPath: '/gallery'
      preLoaderRoute: typeof GalleryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/exports': {
      id: '/exports'
      path: '/exports'
      fullPath: '/exports'
      preLoaderRoute: typeof ExportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/divisions': {
      id: '/divisions'
      path: '/divisions'
      fullPath: '/divisions'
      preLoaderRoute: typeof DivisionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/digital': {
      id: '/digital'
      path: '/digital'
      fullPath: '/digital'
      preLoaderRoute: typeof DigitalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/consulting': {
      id: '/consulting'
      path: '/consulting'
      fullPath: '/consulting'
      preLoaderRoute: typeof ConsultingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog': {
      id: '/blog'
      path: '/blog'
      fullPath: '/blog'
      preLoaderRoute: typeof BlogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/academy': {
      id: '/academy'
      path: '/academy'
      fullPath: '/academy'
      preLoaderRoute: typeof AcademyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AcademyRoute: AcademyRoute,
  BlogRoute: BlogRoute,
  ConsultingRoute: ConsultingRoute,
  ContactRoute: ContactRoute,
  DigitalRoute: DigitalRoute,
  DivisionsRoute: DivisionsRoute,
  ExportsRoute: ExportsRoute,
  GalleryRoute: GalleryRoute,
  LogisticsRoute: LogisticsRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  TradeIntelligenceRoute: TradeIntelligenceRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
